synthesizer-project/synthesizer

synthesizer/parametric/sfzh.py
replace np.float with float to reflect changes made to numpy from version 1.24.0 update
=> Update sfzh.py to prevent numpy >= 1.24.0 issue

generate_grids/download_grids.py
Added functionality to download grids from Google Drive. At the moment only two grids are available but I could add others.
=> added download_grids script

examples/parametric/make_sfzh.py, synthesizer/parametric/sfzh.py
- replaced `summary` with `__str__` in `sfzh` classes
- improved examples
- added ability to add together `BinnedSFZH`
=> updated sfzh

generate_grids/rebin_grid.py
=> updated test grid to extend 100-20000AA at 20AA resolution

synthesizer/plt.py
As the title says. Addresses issue #97.
- [N.A] I have added docstrings to all methods
- [N.A] I have added sufficient comments to all lines
- [N.A] I have made corresponding changes to the documentation
- [N.A] I have added tests that prove my fix is effective or that my feature works
=> Removed the plotting style url

profiling/profile_plot.py
A minimal enhancement to enable quick and dirty profiling. This should allow us to quickly identify bottlenecks in different use cases by profiling example scripts.
- [N.A] I have made corresponding changes to the documentation
- [N.A] I have added tests that prove my fix is effective or that my feature works
=> Added a profiling directory and a simple profiling script

examples/filters.py, examples/parametric/generate_composite_galaxy.py, examples/parametric/make_image.py, examples/parametric/make_sfzh.py, examples/particle/create_flux_image_multifilter.py, examples/sed.py, synthesizer/filters.py, synthesizer/galaxy/galaxy.py, synthesizer/galaxy/parametric.py, synthesizer/imaging/images.py, synthesizer/parametric/morphology.py, synthesizer/sed.py, synthesizer/units.py
- added units to the `Sed` class.
- improved various examples.
- implemented parametric morphology.
NOTE: composite galaxy creation doesn't work as it is waiting for the implementation of Image addition.
NOTE2: many of the methods in `ParametricImage` should be in `Image`.
=> Sed and ParametricImage improvements

synthesizer/galaxy/galaxy.py, synthesizer/sed.py
=> fix filter refs

synthesizer/parametric/sfzh.py
Simple change to allow generating a BinnedSFZH from a SFH array and Z array or float.
=> added functionality to generate BinnedSFZH from array

examples/parametric/generate_sed.py, synthesizer/sed.py
Fixed broadband photometry units by changing `lnu` to `_lnu`.
Expanded example.
=> Steve fixes

setup.py, synthesizer/sed.py
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
=> fix filters, and optional cython

examples/download_camels.sh, synthesizer/load_data.py, synthesizer/sed.py
=> fix camels spectra

synthesizer/line.py
=> Added some more line ratio definitions

docs/source/filters.ipynb, docs/source/index.rst
=> added filters doc ipynb

requirements.txt
=> Update requirements.txt with matplotlib

synthesizer/galaxy/parametric.py
=> fixed get_Q function

docs/README.md
=> Create documentation README.md

.readthedocs.yml
=> fix python inside readthedocs yaml

docs/requirements.txt, docs/source/API.rst, docs/source/conf.py
=> switch to furo for sphinx 7 compatibility reasons

docs/source/conf.py
=> Docs update

docs/source/filters.ipynb, synthesizer/filters.py
=> fix typo in filter collection class

docs/source/filters.ipynb, synthesizer/exceptions.py, synthesizer/filters.py
Adds a method (`find_filter`) to take a rest frame wavelength and return the filter (and print the filter code) corresponding to that wavelength either in the rest frame or the observer frame.
Also renovated the Filter docs and included a demonstration of `find_filter`.
Closes #217
=> Adds a function to find a filter based on wavelength.

synthesizer/load_data.py
=> added astrid load method, updated doc strings

docs/source/conf.py, docs/source/grids/grids.rst, docs/source/grids/photoionisation.rst
=> Expanded Grid Documentation

examples/parametric/plot_equivalent_width.py, synthesizer/base_galaxy.py, synthesizer/sed.py
=> Fixed issues with plot_equivalent_width example

synthesizer/sed.py
=> fix units error raised in docs

.github/workflows/publish_docs.yml
=> fix publish workflow

.github/workflows/publish_docs.yml
=> fix publish docs requirements install

synthesizer/particle/galaxy.py
Gamma dust, method now has a few optional added arguments. Docstring is also updated.
- Enhancement
=> gamma dust, added args and updated docstring

examples/general/plot_dustcurves.py, synthesizer/base_galaxy.py, synthesizer/dust/attenuation.py, synthesizer/dust/emission.py
This cleans up the structure of the dust attenuation and emission implementation. It:
- Closes #281.
- Updates doc strings to Google format.
- Removes redundant mutable default arguments in favour of keyword arguments.
- Implements an inheritance structure.
- Removes various style issues.
- Document
- Enhancement
=> Clean dust structure and style fixes

examples/grids/plot_interp_grid.py, synthesizer/grid.py
Does what it says on the tin. Turned out to be a trivial switch, if somewhat confused by their examples. The example has been modified too.
- Enhancement
=> Using spectres not scipy for grid interpolation

synthesizer/base_galaxy.py
Removed the duplicated grid extraction in the `get_spectra_pacman`. Now either all particles are calculated (if no age threshold has been passed) at once or young and old are calculated separately and summed.
Also added a handful more comments to the method to help with readability.
- Bug
=> Removed doubled grid calculations in pacman

.github/workflows/publish_docs.yml, .github/workflows/python-app.yml
The black hole grid is also now on Google Drive.
Can remove it from the history once this is merged.
- Enhancement
=> Downloading blackhole grid

examples/cosmo/plot_sc-sam.py, synthesizer/load_sam_data.py
Added verbosity flag to SAM methods. 
Updated example to remove close statements after show, as these stop the plot showing in the docs.
- Enhancement
=> Small sam changes

synthesizer/exceptions.py, synthesizer/filters.py
Closes #378, DWISOTT 
- Enhancement
=> Raise a more meaningful error when the svo filter service is down

src/synthesizer/parametric/sfzh.py
Add the exponentially declining, delayed exponentially declining and double power law SFHs to the parametric SFH class.
Also clears up some of the sfzh docstrings and init, hopefully closing #329 
- Enhancement
=> Add parametric models

docs/source/installation.rst
=> Update installation.rst details

.github/workflows/python-app.yml
Remove reference to broken_examples directory
- Enhancement
=> Update workflow to remove old reference

docs/CONTRIBUTING.md
=> Contribution style updates

.gitignore
=> Properly ignoring _version.py

src/synthesizer/dust/attenuation.py, src/synthesizer/dust/emission.py
- Bug
Certain functions require use of units in the attenuation and emission scripts. Added checks for unyts at required places.
=> implemented unyt fixes in dust modules

src/synthesizer/utils.py
=> updated planck doc string

src/synthesizer/components/stellar.py
Fixes bugs in the pacman model where non-cloudy grids will not run.
- Bug
=> Update pacman to accept non-cloudy grids

README.md, docs/source/installation.rst
DWISOTT. Updated docs installation page with non-editable instructions, and added small section to README.
- Document
=> Update install instructions

pyproject.toml
DWISOTT
`dust_extinction` fixed the issue [here](https://github.com/karllark/dust_extinction/issues/200)
- Enhancement
=> Removing astropy version pinning

src/synthesizer/load_data/load_camels.py, src/synthesizer/particle/galaxy.py
Fixes a small units bug in gamma method. Also adds comment to describe units.
- Bug
=> Fix gamma bug

src/synthesizer/filters.py
=> add URL to SVO filter error

examples/parametric/generate_lines.py
- Document
- [x ] I have read the [CONTRIBUTING.md]() -->
- [ x] I have added docstrings to all methods
- [ x] I have added sufficient comments to all lines
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no pep8 errors
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
=> changed galaxy.get_line to galaxy.stars.get_line in docs

docs/source/cosmo/cosmo_example.ipynb, docs/source/parametric/generate_sed.ipynb, docs/source/sed.ipynb, examples/general/plot_quiescent_colours.py, examples/parametric/plot_observed_sed.py, examples/parametric/plot_sed.py, src/synthesizer/photometry.py, src/synthesizer/sed.py, src/synthesizer/survey.py, src/synthesizer/units.py
DWISOTT:
`broadband_luminosities` -> `photo_luminosities`
`broadband_fluxes` -> `photo_fluxes`
Closes #490.
- Enhancement
=> Introduces a better name for photometry

src/synthesizer/grid.py
There wasn't really a nice way to visualise a grid across the wavelength range for all grid cells. This PR introduces a simple animation method which steps through the wavelength bins at some requested fps. 
- Enhancement
=> Introduce a grid animation method

examples/parametric/plot_equivalent_width.py
=> Changes to plot_equivalent_width.py

src/synthesizer/load_data/load_bluetides.py, src/synthesizer/load_data/load_camels.py, src/synthesizer/load_data/load_flares.py, src/synthesizer/load_data/load_simba.py, src/synthesizer/particle/galaxy.py
Changed all instances of metals to metallicities, to reflect wider naming convention.
=> changed instances of metals to metallicities

docs/source/parametric/generate_sed.ipynb, docs/source/sed.ipynb, src/synthesizer/sed.py, src/synthesizer/utils.py
=> Added a function to visualise a spectra as a rainbow

src/synthesizer/components/stellar.py
=> add nebular continuum method on stellar component

src/synthesizer/load_data/load_illustris.py
Fix typo in load TNG method. Added small doc fixes.
- Bug
=> Fix typo, add docs in TNG load data method

profiling/plot_massif.py, profiling/profile_mem_int_spectra.py, profiling/profile_mem_part_spectra.py, profiling/profile_time_int_spectra.py, profiling/profile_time_part_spectra.py
=> Adds a plotting script for interfacing with valgrind and profiling scripts

src/synthesizer/emission_models/base_model.py
Because related model spectra/lines are called recursively it was possible to construct a model that would delete spectra that were later needed. This is now fixed.
- Bug
=> Ensuring emissions aren't prematurely deleted

docs/source/emission_models/premade_models/stellar_models.ipynb, src/synthesizer/emission_models/__init__.py, src/synthesizer/emission_models/stellar/__init__.py, src/synthesizer/emission_models/stellar/pacman_model.py
Added a simplified version of `PacmanEmission` that wraps it but sets fesc=0.0 and fesc_ly_alpha=1.0.
- Enhancement
=> Added an escape fractionless `PacmanEmission` called `ScreenEmission`

src/synthesizer/conversions.py
Conversions module now offers the possibility to convert attenuations to optical depths, optical depths to attenuations and optical depths from any given band to v-band optical depths. 
Closes #670, closes #671.
- Enhancement
=> Introduced tau conversions.

docs/source/imaging/particle_data_cube.ipynb, docs/source/imaging/particle_imaging.ipynb, docs/source/imaging/property_maps.ipynb, docs/source/lines/galaxy_lines.ipynb, docs/source/spectra/stars.ipynb, examples/cosmo/cosmo_example.py, examples/cosmo/test_aperture_mask.py, examples/cosmo/test_los_spectra.py, examples/cosmo/test_parametric_young_stars.py, src/synthesizer/load_data/load_camels.py, src/synthesizer/particle/galaxy.py, src/synthesizer/particle/stars.py, tests/data/create_camels_small_snap.py
Add Swift-EAGLE CAMELS data loader. 
Other changes:
- Argument names on camels data loader methods updated to be more general - rather than `fof_*` all now named `group_*`
- Metallicity floor property properly initialised
- Star and gas particle loading on initialisation fixed to remove default errors
- Enhancement
=> Swift eagle loader

src/synthesizer/particle/stars.py
fix for no particle case
- Bug
=> Fix parametric young stars masks

src/synthesizer/download_data.py
We quickly saturated the free dropbox bandwidth. However, @stephenmwilkins has Dropbox pro which is limitless. This PR switches over the downloads to target files there. It also cleans up the source a little bit by defining all the file metadata in one place. 
- Enhancement
=> Switching to a limitless bandwidth dropbox

docs/source/filters/filters_example.ipynb, src/synthesizer/filters.py
=> Small fix for Filter.find_filter to ensure unit consistency

src/synthesizer/download_data.py
DWISOTT, no pointing waiting forever for the primary server to fail.
- Enhancement
=> Added a timeout for the primary data server to stop wait time

src/synthesizer/components/blackhole.py, src/synthesizer/emission_models/agn/unified_agn.py, src/synthesizer/emission_models/base_model.py, src/synthesizer/emission_models/operations.py
Squashing various bugs affecting line emission from blackholes. For example setting the luminosity to `0.0` instead of `0`.
Code works but I haven't verified the results make sense yet.
=> Fix blackhole line bugs

src/synthesizer/parametric/sf_hist.py
=> Quarantining dense_basis import to avoid print

.github/workflows/publish_docs.yml, docs/source/components/gas.ipynb, src/synthesizer/download_data.py, src/synthesizer/grid.py
- Fixed the data download for publishing the docs so the dust grids are downloaded.
- Normalising the AGN grids so the docs aren't totally unphysical. (quick fix until such a time that @stephenmwilkins updates the test grids).
- Clarified the arbitrary kwargs in the gas docs.
- Enhancement
=> Giving the docs some TLC

src/synthesizer/instruments/filters.py
=> Fix unit error in filters.py to address PR 802

README.md
DWISOTT 
Closes #745 
- Document
=> Including test data download in readme

src/synthesizer/parametric/stars.py
Setting the initial mass had no effect if a SFZH array was provided to a parametric `Stars` object. Although passing an array and an initial mass doesn't make total sense it's confusing that passing both did not scale the total initial mass. Therefore the requested initial mass is now respected regardless of the method of SFZH definition. 
Closes #620 
- Bug
=> Always scale by the initial mass when initialising a parametric Stars object

src/synthesizer/photoionisation/cloudy17.py, src/synthesizer/photoionisation/cloudy23.py
- Enhancement
Added the option to use ISM grain type in cloudy consistently
=> Add ISM grain type from cloudy

.github/workflows/deploy.yml
Adding a workflow to deploy to PyPi
- Enhancement
=> Adding a deployment workflow 

.github/workflows/python-app.yml, README.md, docs/CONTRIBUTING.md, docs/source/advanced/config_options.rst, docs/source/getting_started/installation.rst, pyproject.toml
DWISOTT, README and docs detailing installation have been updated. README has also been simplified and points at the docs for more involved installations.
- Document
=> Update installation instructions in light of working PyPI deployment

src/synthesizer/pipeline/pipeline.py, src/synthesizer/pipeline/pipeline_io.py
Fixes a bug in the name of the collective IO flag.
- Bug
=> fix collective io typo

docs/source/components/stars.ipynb
=> Fix bug in parametric SFH documentation

src/synthesizer/downloader/_data_ids.yml, src/synthesizer/grid.py, src/synthesizer/utils/ascii_table.py
This PR lays the groundwork for working with the new grid files. All this does so far is translate the new grid file format for lines into the old dictionaries, including full backward compatibility with old grids. 
Any further updates will remove all backward compatibility since we will be looking towards using all the new attributes and data.
- Enhancement
=> Laying the ground work for the new line format

conftest.py, src/synthesizer/particle/particles.py, tests/test_particle_stars.py
DWISOTT. Also modifies the `get_radii` method to return the radii when called.
- Enhancement
=> Add radii test

src/synthesizer/load_data/load_eagle.py
- Bug
- Document
- Enhancement
=> modified assign_galaxy_properties

docs/joss_paper/paper.md
Changed affiliaition to Institute of Space Sciences and Astronomy, University of Malta, Msida MSD 2080, Malta
- Document
=> Updated Affiliation.md
