synthesizer-project/synthesizer

- synthesizer/galaxy/particle.py
Implemented spectra creation speed up in Galaxy.generate_intrinsic_spectra where a mask is applied to the weights array to avoid spending time calculating 0xvalue which hogs time but contributes nothing to the sum. 
Also added Numpydoc doc strings and had a general clean up and comment of the function.
> generate_intrinsic_spectra speed up

- examples/grids/lines.py
- synthesizer/cloudy.py
- synthesizer/grid.py
- synthesizer/line.py
- Added a `LineCollection` class. This can easily return line ratios/diagrams (E.g. BPT).
- Added a `LineRatios` data class for holding line ratio definitions.
- Modified Grid to return a `LineCollection`. 
- update grid/lines example to show functionality.
> More line improvements

- synthesizer/galaxy/particle.py
Small fix to save intrinsic spectra when calculating dust attenuated
- [ x ] Bug
> Fix intrinsic save

- examples/cloudy/run_cloudy.py
- generate_grids/cloudy/make_cloudy_input_grid.py
- synthesizer/cloudy.py
This PR describes changes mostly to the function to create cloudy input scripts. What I've done is separate out the spectral shape definition to leave a more generic input creation function. The spectra shape definitions have been separated into a separate class (`ShapeCommands`). At the moment this class holds a single function for using tabulated SEDs but it will be expanded to include other possibilities, including a Blackbody and cloudy's in-built AGN model. This PR is needed to enable proper development of both those.
Like all the cloudy/grid generation this is currently poorly documented because it's in transition and rather niche.
> Cloudy improvements

- setup.py
Bug in setup.py that rpevented extensions being installed with `pip`
- [ x ] Bug
> fix c extension paths

- examples/abundances.py
- synthesizer/abundances.py
- synthesizer/cloudy.py
I have improved the clarity of `abundances.py` by calculating the total, gas, and dust abundance patterns. For no depletion gas == total and dust = 0.0. Cloudy should take gas by default since we specify grains later for self-consistency.
Example is updated as is `cloudy.py`.
No documentation yet, but this can be generated from the example.
> Abundances improvements

- synthesizer/imaging/scene.py
Implemented a catch for when an integrated SED is passed to image/IFU creation. 
Also included a catch for when the number of stars/positions doesn't agree with the SED. 
closes #211
> A better error for when an integrated SED is passed to imaging

- examples/parametric/create_parametric_image.py
- synthesizer/parametric/galaxy.py
Closes #156.
Introduces a mask for non-zero indices in SFZH. Removing these redundant calculations results in a 1/3 speed up, possibly more for a realistically large grid which would have more 0s to remove. 
Also improved the documentation of the function. 
I have confirmed the answer given by examples is unchanged by this change.
> Removing multiplications by 0 in Parametric generate_lnu

- synthesizer/filters.py
Following the Slack discussion, this PR implements `FilterCollection.resample_filters` which enables the resampling of filters on a wavelength array.  
This method is then called during initialisation if `new_lam=None` and finds a wavelength array that encompasses all included `Filter`s at the resolution of the highest resolution filter curve. Thus fixing the bug encountered when not passing a wavelength array.
> Adds the ability to create a FilterCollection without specifying a wavelength array

- examples/parametric/generate_lines.py
- synthesizer/line.py
Closes #246.
Overloads the iteration methods on `LineCollection` to enable `for l in lines:` iteration syntax.
Note that lines.py needs a lot of work on the documentation side of things and docs in general need writing to describe line interactions. This is beyond the scope of this PR. 
- [N.A] I have made corresponding changes to the documentation
> Introduced for l in lines: syntax

- synthesizer/sed.py
Due to the addition of absorption feature labels as the first column in 'uv_dict', all indices for the list 'index' required to be incremented by 1 (i.e., index[0] becomes index[1], etc...).
> Fixed Issue with calculate_ew absorption feature indices

- synthesizer/filters.py
Closes #264. 
Introduces a wavelength resolution argument for resampling filters. This means its impossible to unknowingly derived an OTT wavelength array from SVO filters if the user does not provide a wavelength array.
> Derived wavelength resolution fix

- synthesizer/load_data.py
- synthesizer/particle/galaxy.py
- synthesizer/particle/stars.py
Fixes three separate issues / bugs, of varying degrees of importance:
- fixes a bug in the `_prepare_sed_args` particle galaxy method, that meant grid metallicities were passed in linear, whilst particle metallicities were in log
- Fixes the load data method for IllustrisTNG to fix some unit issues, and filter out wind particles
- Fixes the Stars class docstring to give the correct units on particle ages (yr, not Myr)
- Bug
> Grid spectra fixes

- .github/workflows/publish_docs.yml
- .github/workflows/python-app.yml
- docs/requirements.txt
- docs/source/conf.py
Documentation updates 
- Compile docs as part of testing workflow, will fail if docs fail. This acts as a way of testing the examples directory, since these are run as part of the sphinx-gallery workflow
- Publishes compiled docs to github pages when a PR is merged to main
- Enhancement
> compile docs in workflow

- synthesizer/units.py
Uses the 'galactic'` base class (see [here](https://unyt.readthedocs.io/en/stable/usage.html#other-unit-systems)) for solar masses, to avoid overflow errors when handling 32 bit floats and masses > 1e10 Msun.
- Bug
> Use galactic base class for unyts to avoid overflow errors

- .github/workflows/python-app.yml
- docs/source/imaging/particle_imaging.ipynb
- synthesizer/base_galaxy.py
- synthesizer/particle/blackholes.py
- synthesizer/particle/galaxy.py
- synthesizer/survey.py
Fixes names of particle methods to be consistent with adopted grid naming scheme and the exiting integrated methods. 
Also the following minor fixes:
- fixes a bug in the workflow whereby pytests on doc notebooks would fail but wouldn't interrupt the workflow, as they were run individually
- adds some attributes to the particle/blackholes class that led to failures in one of the docs
- Bug
> Fix particle spectra methods

- synthesizer/particle/galaxy.py
Fix so that method returns zero rather than nan
- Bug
> set gamma to zero for zero gas mass galaxies

- synthesizer/grid.py
This PR closes #315. It does so by checking if a file extension has been handed to the Grid. If so it strips it from the name and stores it to be added to the full path. If an extension has not been passed the default ".hdf5" is assumed. This allows users to pass ".h5" extensions which was previously not possible.
There is a lot of missing documentation in `grid.py` but I have at least added a description of the attributes in the class doc string in this PR. **Please check I'm correct about what `self.parameters` is**.
- Enhancement
> Better handling of grid file extension

- synthesizer/particle/galaxy.py
Introduced logic to error if any of the required properties are missing for LOS dust optical depth calculation.
Closes #296
- Bug
> Added checks for required properties

- synthesizer/grid.py
Temporary fix for grid filenames including `.`s. The code for now checks if the last string split by "." is "hdf5" or "h5".
In the long run filenames should be modified to exclude fullstops. Adopting concatenation for version numbers and `p` to present points in real parameters.
- Bug
> Accounting for . in grid file paths

- synthesizer/dust/attenuation.py
- synthesizer/particle/galaxy.py
This PR brings the particle spectra in line with the integrated spectra. It:
- Adds particle-specific spectra methods to `particle.galaxy.Galaxy`.
- Adds an `apply_attenuation` method which can be used any number of times to apply different attenuation of sources, including masks. For now, this just overwrites the "attenuated" key each time. Open to suggestions of an alternative key nomenclature. 
- Modifies dust attenuation models to allow arrays of `tau_v`.
It does NOT:
- Move particle spectra onto particle objects.
- Isolate integrated spectra to the galaxy. 
That will be done on a future PR including BH and Gas spectra.
- Enhancement
> Updating particle spectra and particle attenuation

- .github/workflows/python-app.yml
- docs/source/imaging/parametric_imaging.ipynb
- docs/source/imaging/particle_imaging.ipynb
- examples/particle/plot_create_survey_imgs.py
- tests/get_test_grid.sh
This PR deletes the test grid and replaces it with a GitHub action that installs `gdown` (a pip installable interface to Google Drive) and downloads a bpass grid from [here](https://drive.google.com/file/d/1txY9PY-ejtRaMSZorpZSxGPsm6muvh9X/view?usp=sharing). 
This test grid is named `test_grid.hdf5` and stored in `tests/test_grid` meaning all examples still run without issue (modulo a couple of imaging ones that needed modifying to account for the extremely high wavelength resolution of the BPASS grid).  We can change the grid downloaded to any grid we want and the action will always rename it test_grid.hdf5.
This required adding a Google Drive API key to the repo's secrets. We can reuse this API key to store any data we want and download it in the action.
A user can also download the …
> Removing test grid with Google drive Action

- docs/source/imaging/particle_imaging.ipynb
- examples/particle/plot_compare_parametric_particle.py
- examples/particle/plot_generate_coordinates.py
Reduce the particle number in a few examples to reduce the compute time, as this seems to be causing workflows to fall over in some instances
- Bug
> reduce compute of various examples and docs

- docs/source/parametric/generate_lines.ipynb
- synthesizer/parametric/galaxy.py
Bug in attenuated line generation for parametric galaxies. Correspondingly, have changed the nebular and stellar attenuation name to BC (birth cloud) and ISM. Also edited `get_line_screen` so that it did not add line attenuation twice.
Closes #357 
- Bug
- Enhancement
> 357 parametric line att

- docs/source/parametric/generate_composite_galaxy.ipynb
- examples/parametric/plot_composite_galaxy.py
Could Close #359 if the citied segfault is indeed to do with the memory available as I'm guessing. Loading the new test grid the images would be ~(50, 50, 80000). Overkill for this example. If this PR does not error then this is almost certainly the case and this PR does close the issue.
The fix is to pass a lower resolution wavelength grid at `Grid` instantiation. As in other imaging examples. Sadly this will always be a necessary evil for IFU creation. Although it is computationally more efficient to make the IFU and make images from it we may want to pivot and only make IFUs specifically when they are wanted. 
- Bug
> Reducing memory overhead in plot_composite_galaxy

- synthesizer/parametric/sfzh.py
This PR changes `imshow` to `pcolormesh` to ensure the alignment between SFZH grid plot and the 1D plots on the sides.
Closes #251 
- Bug
> Fixed SFZH plot alignment

- setup.py
- synthesizer/extensions/integrated_spectra.c
- synthesizer/extensions/particle_spectra.c
- synthesizer/particle/galaxy.py
@christopherlovell observed that integrated spectra were taking surprisingly long to compute for a high-resolution wavelength array. This PR solves that while significantly improving the readability, documentation, and (particle) performance of the spectra extensions.
- Spectra extensions are now divided into an integrated and particle extension.
- Wavelength elements are looped over only once for each non-zero weight in integrated spectra computation.
- Particles now update the spectra during recursion removing some unnecessary looping.
- All function descriptions are now complete.
In doing this simplification and optimization the results changed but now seem much more sensible than what was there previously. I likely uncovered and fixed an indexing bug without realizing it in this …
> Improves the performance of spectra creation

- docs/source/blackholes/grids.ipynb
- docs/source/sed.ipynb
- synthesizer/filters.py
- synthesizer/sed.py
np.concatanate(x, y) -> np.concatenate((x, y))
Also fixes unut related errors that have appeared in #372 and this PR. The fix for these was to use the unitless version of attributes in several filter functions and in the blackhole grid docs. I presume a package updated changing the behaviour in these situations. Particularly when using `np.trapz` but also `SED(lam, lnu)` so probably a unyt update.
- Bug
> Fixed typo in sed.concat

- docs/source/grids/grids_example.ipynb
Corrected "This object takes the lcoatino of the grids on your system" to "This object takes the location of the grids on your system" in grids_example.ipynb
- Document
> Typo correction

- requirements.txt
- src/synthesizer/dust/attenuation.py
- Enhancement
Changed the Calzetti attenuation curve definition to remove infinities and nan at longer wavelengths.
I have also removed the from the requirements dust_attenuation package which is no longer used.
Closes #142
> Calzetti fix

- src/synthesizer/components/stellar.py
- src/synthesizer/particle/stars.py
Currently the age mask on a stars particle object compares in years, but is expecting `young` / `old` to be in Myr. 
- added method to check the units of `young` and `old` ni all the specrta generation methods
- fixes a bug in `_prepare_sed_args` where the particle number was set to the original array size, not the size of the mask
- docstring updated
- Bug
> Fix age mask units

- src/synthesizer/grid.py
Fix conditions the wrong way around
- Bug
> Fix bug in grid __str__ method

- docs/source/sed.ipynb
- src/synthesizer/sed.py
Added `luminosity_nu`, `luminosity_lambda`, and `wavelength` as aliases to `lnu`, `llam`, and `lam` respectively. Added description to sed doc notebook.
Closes #410 
- Bug
- Document
> Add luminosity and wavelength aliases

- docs/source/parametric/generate_composite_galaxy.ipynb
Instead of `stars` the bulge stars object was accidentally named `sfzh` from the old version resulting in the disk being plotted twice. This is now fixed with some extra parameter tweaking for a "pleasing" result.
- Bug
> Fixed the bulge in composite galaxy docs

- src/synthesizer/components/stellar.py
- src/synthesizer/sed.py
added a `kwargs` argument to the stellar component `plot_spectra` method that is passed to the sed `plot_spectra` method, to provide more control.
- also fixed a small typo in sed.py
- Enhancement
- [] I have made corresponding changes to the documentation
- [] My changes generate no pep8 errors
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
> Plot keywords in component plot method

- examples/parametric/plot_observed_sed.py
- src/synthesizer/base_galaxy.py
- src/synthesizer/exceptions.py
This PR adds the ability to calculate all observed spectra on a galaxy (`get_observed_spectra`) for both combined and component spectra (gas and black holes need to be included once implemented).
It also introduces a `MissingAttribute` error class to be used when an operation can't be performed because it requires an attribute which is `None`.
Closes #416 
- Enhancement
> galaxies should have a get observed spectra method

- examples/general/plot_dustcurves.py
- src/synthesizer/dust/attenuation.py
Fixes data directory for `npz` files for the Milky Way attenuation in Narayanan+18. also updates example script to plot these.
We should look into extracting the relevant data into plain text files, as npz files are a security risk.
- Bug
> Fix attenuation n18

- src/synthesizer/sed.py
DWISOTT. This case was previously missing!
- Bug
> Adds missing case for combining two 1D spectra

- src/synthesizer/particle/stars.py
Changed the logic to be greater than/less than or equal to.
Closes #432. 
- Bug
> Not including particles on the grid edges in grid checks

- src/synthesizer/imaging/scene.py
- src/synthesizer/load_data/load_camels.py
- src/synthesizer/load_data/load_flares.py
- src/synthesizer/load_data/load_scsam.py
- src/synthesizer/load_data/load_simba.py
- src/synthesizer/particle/galaxy.py
Fixed the issue in the particle imaging documentation. For some reason the units I had added to automatically convert everything to the global system had been removed (I assume in the move). Thus the kpc units of the loaded data were assumed to be Mpc and the images failed completely.
- Bug
> Fixed the particle imaging docs.

- examples/particle/plot_compare_grid_assignment.py
- examples/particle/plot_compare_parametric_particle.py
- examples/particle/plot_single_star_test.py
- setup.py
- src/synthesizer/components/stellar.py
- src/synthesizer/extensions/integrated_spectra.c
- src/synthesizer/extensions/macros.h
- src/synthesizer/extensions/particle_spectra.c
- src/synthesizer/extensions/sfzh.c
- src/synthesizer/extensions/weights.h
- src/synthesizer/parametric/stars.py
- src/synthesizer/particle/stars.py
This PR addresses the issues observed when comparing parametric and particle derived spectra. 
The code surrounding this process was somewhat convoluted due to the parts that needed to handle arbitrary dimensions. This complexity had lots of scope to introduce mistakes and one had been introduced in the assignment of grid indices. The cause of this issue was a logical expression which should have been `>=` but was just `>`. 
This PR has not only fixed the code and simplified it dramatically it:
- Removes the recursive method in favour of a clearer iterative method that still works for arbitrarily many directions.
- Closes #278, by the introduction of a `grid_assignment_method` argument which can either take `"cic"/"CIC"` to use the old "interpolation" like method, or `"ngp"/"NGP"` to use …
> Fix and complete sanity check of particle spectra derivation

- src/synthesizer/sed.py
The `apply_attenuation` method on Sed references a `tau_v` array on Sed, rather than the argument passed to the function, leading to an error.
This patch fixes the reference to the argument
- Bug
- [x ] I have added docstrings to all methods
> FIx self reference in apply_attenuation

- pyproject.toml
DWISOTT. Also sets the astropy version to ensure workflows don't fail (this is also set elsewhere). 
Issue raised on `dust_extinction` related to astropy version issue: https://github.com/karllark/dust_extinction/issues/197
- Enhancement
> Remove dust_attenutation dependency and set astropy version

- src/synthesizer/particle/stars.py
This PR:
- Makes the grid bounds error `False` by default so it has to be actively turned on when debugging.
- Adds a report of the percentage of points above or below the limits.
- Closes #440 
For now, this is specific to age and metallicity but can be easily generalised in the future when needed.
- Enhancement
> Improve the out of grid bounds error

- src/synthesizer/load_data/load_camels.py
Fixes the edge case where moving mesh codes, such as gizmo, have no inherent stellar smoothing length information. Also fixes a small bug where the TNG and Astrid CAMELS load scripts did not include the redshft.
- Bug
> Fix case where CAMELS-Simba has no stellar smoothing lengths

- src/synthesizer/components/stellar.py
- src/synthesizer/imaging/images.py
- src/synthesizer/imaging/scene.py
- src/synthesizer/particle/blackholes.py
- src/synthesizer/particle/galaxy.py
- src/synthesizer/particle/gas.py
- src/synthesizer/particle/particles.py
- src/synthesizer/particle/stars.py
The error in the title is because only one parent class can have slots in multiple inheritance. In reality, the saving from slots was entirely negligible so it's better to remove them entirely.
In certain cases `__slots__` have been replaced by `attrs` to enable looping over all attributes in certain checks and additions. 
Closes #415 
- Bug
> Removing __slots__ to fix `TypeError: multiple bases have instance lay-out conflict`

- docs/source/grids/grids_example.ipynb
- src/synthesizer/grid.py
This PR implements `Grid.get_sed` to convert a particular spectra grid to a `Sed` object enabling all of the Sed methods to be used on a whole `Grid`. This is demonstrated in the `Grid` docs. 
Closes #333 
- Enhancement
> Convert a `Grid` to an `Sed`

- src/synthesizer/extensions/integrated_spectra.c
- src/synthesizer/extensions/particle_spectra.c
- src/synthesizer/extensions/sfzh.c
- src/synthesizer/extensions/weights.h
- src/synthesizer/particle/stars.py
Although not a common use case it would be nice to be able to give star particles particle specific escape fractions (i.e. based on age or metallicity). This PR enables this as a possibility.
- `fesc` can be a single value. If it is an array full of that value is made to pass to the C extension. This is short lived enough and only 32 bit so has a minimal effect on footprint.
- `fesc` can also be passed as any array.
- Since the integrated spectra extension limits lam loops by calculating the weight grid first and then applying it to spectra the escape fraction is combined into the weights, this is all hidden in the backend but this approach is the only way to maintain this optimisation and enable the `fesc` array. It works but is worth noting.
- Closes #124 
- Enhancement
> Enabling per particle escape fractions

- src/synthesizer/extensions/weights.h
Fixes a small bug in CIC grid assignment where weights at the lower edge of the grid were assigned a weight fraction of zero. Led to segfaults in some cases where the entire weights grid was empty.
- Bug
> wrong weight fraction for lower edge of grid cases

- docs/source/cosmo/cosmo_example.ipynb
Hardcoded limits were causing blank plots in the cosmo docs. These have been removed.
- Bug
> Fixed the limits on plots in cosmo_examples.ipynb

- src/synthesizer/line.py
> added theoretical BPT ratios for Kewley, Kauffmann

- examples/particle/plot_los_spectra.py
- src/synthesizer/particle/galaxy.py
Introduces `particle.Galaxy.integrate_particle_spectra` which will integrate all `particle_spectra` on all components and store them in the component `spectra` attributes. 
This PR also introduces an example demonstrating this behaviour in `examples/particle/plot_los_spectra`. This example also makes a plot of the attenuated and incident spectra which was absent from the other los example which focuses on accuracy and runtime. 
This PR does not implement this method on the components themselves since most (if not all?) cases where this is needed are at the galaxy level requiring multiple components to calculate the optical depths. However, if people disagree with this assessment they can be easily implemented on the components.
Closes #488 
- Enhancement
> Introduced method to integrate particle spectra

- src/synthesizer/base_galaxy.py
`get_spectra_dust` now correctly uses the stellar spectra attached to a galaxy.
- Bug
> Fixing `get_spectra_dust`

- docs/source/filters.ipynb
- src/synthesizer/filters.py
You can now make a `FilterCollection` from a list of existing `Filter` objects. In addition:
- Addition now ensures the added `Filter`s are on the same wavelength range.
- Documentation has been expanded to include a demonstration of this change.
- Documentation now explains the single wavelength array for a `FilterCollection` and behind the scenes behaviour to maintain it.
Closes #504 and closes #505 
- Enhancement
> Allow `FilterCollection`s to be made from existing `Filter`s

- src/synthesizer/filters.py
DWISOTT.
Also allows multiple calls to the filter collection, by passing in an existing figure and / or axes object on which to plot.
- Enhancement
> Allow kwargs to be passed to plot call in FilterCollection plot method

- docs/source/imaging/particle_imaging.ipynb
- examples/cosmo/test_los_spectra.py
- examples/particle/plot_los_spectra.py
- src/synthesizer/extensions/los.c
- src/synthesizer/kernel_functions.py
- src/synthesizer/load_data/load_camels.py
- src/synthesizer/load_data/load_flares.py
- src/synthesizer/load_data/load_simba.py
- src/synthesizer/particle/galaxy.py
- src/synthesizer/particle/stars.py
- src/synthesizer/sed.py
Fixes FLARES method for loading data. Also includes a number of other relatively small changes and fixes, summarised below:
Changelog:
- Updated kernel class to be capitalised (kernel -> Kernel)
- Fixed error in the los extension where the length ratio was not square rooted
- Simplified LOS extension calculation
- Changed all `load_data` methods to load lengths (coordinates, smoothing lengths, etc.) in physical, rather than comoving coordinates
- Adds the `dust_to_metal_vijayan19` method for calculating the DTM ratio from galaxy properties, detailed in [Vijayan+21](https://ui.adsabs.harvard.edu/abs/2020arXiv200806057V/abstract)
- Fixes an error in the `generate_lnu` for stars component where an empty array was returned with the wrong dimensions
- Adds a `sum` method to `Sed` to collapse …
> Fix FLARES load

- src/synthesizer/particle/stars.py
> fix unit of ages in particle stars documentation

- src/synthesizer/photometry.py
- src/synthesizer/sed.py
- src/synthesizer/units.py
Fixes a bug where photometry was not stored in spectral flux/luminosity density units, leading to issues with downstream tasks and removes the `rest_frame` flag when instantiating a `PhotometryCollection`.
- Photometry is now in spectral flux/luminosity density units.
- Whether a flux or luminosity has been passed is automatically detected.
- All rest frame vs observer frame nomenclature has been removed.
- Small fix applied to unit formatting on plot axes.
- `Sed.get_fnu` associates the `fnu` or `lnu` units to the photometry after calling `apply_filter`. This was returning `dimensionless` quantities. Which is fine when the units system isn't modified but would have led to conversion issues if the system had been modified to use differing units for photometry and spectra.
While the …
> Fix photometry units and intialisation

- src/synthesizer/sed.py
Now `get_fnu` will call automatically `get_fnu0` if a redshift of 0 is passed. This avoids infinities in the distance modulus. Note that this will ignore any explicitly stated IGM since it makes no sense at a distance of 10 pc. We could alternatively allow the user to provide a distance at which to calculate flux instead... but that feel arbitrary and over complex. This is simply to handle the case when a user should have called `get_fnu0` instead of `get_fnu` (a mistake I have personally made).
Closes #525.
- Enhancement
> Handling z=0 in get_fnu

- docs/source/cosmo/cosmo_example.ipynb
- docs/source/galaxies/galaxy_obj.ipynb
- src/synthesizer/base_galaxy.py
- src/synthesizer/components/blackhole.py
- src/synthesizer/components/stellar.py
- src/synthesizer/particle/particles.py
This PR introduces wrappers on a `Galaxy` and components for getting photometry. These methods take a filter collection and compute the photometry for all spectra nested within a galaxy. This includes particle spectra if they exist. 
This has been demonstrated in the cosmo_example docs. 
This also implements improvement on `get_observed_spectra` which hadn't been updated to include black holes and didn't have protections for when a component was `None`.
Closes #515 
Requires #519 
- Enhancement
> Introduced collective photometry methods on `Galaxy` and components

- src/synthesizer/photometry.py
- src/synthesizer/sed.py
DWISOTT: automatic parsing of `unyt` units into an axis label was missing whitespace and a handler for powers.
- Bug
> Fixed powers and whitespace in spectra labels

- src/synthesizer/particle/blackholes.py
- src/synthesizer/utils.py
I have no idea how this has slipped through the cracks for so long but the expansion of floats into particle arrays for particle spectra used the number of BH derived from the mask rather than the number of BH in a `BlackHoles` object. This meant the mask was the wrong shape when applied.
There was also an issue when a single particle was passed to a black hole object with units and it passed through the `value_to_array` logic without being captured correctly and triggered an error.
- Bug
> Fixed agn masking in `_prepare_sed_args`

- docs/source/grids/grids_example.ipynb
- src/synthesizer/filters.py
- src/synthesizer/grid.py
DWISOTT: now there's a simple method to unify a grid and filter collection. This has also been demonstrated in the docs.
This also allows a grid to be instantiated with a filter collection to automatically perform the unification at instantiation.
- Enhancement
> Adds a method to interpolate a Grid onto a `FilterCollection` wavelength array

- .github/workflows/publish_docs.yml
The old download script hadn't been removed from the docs workflow.
- Bug
> Remove depracated script from docs workflow

- src/synthesizer/components/stellar.py
In `get_spectra_pacman` you could provide a set of arguments which led to the `"emergent"` key never being combined from the young and old components. 
Closes #550.
- Bug
> Fixing emergent spectra issue #550

- src/synthesizer/components/stellar.py
- src/synthesizer/dust/emission.py
- src/synthesizer/grid.py
- src/synthesizer/line.py
- src/synthesizer/particle/blackholes.py
- src/synthesizer/utils.py
This PR cleans up grid.py a bit.
- The initialisation was previously pretty impenetrable. This has now been packaged up into private methods which do specific jobs to aid interpretation.
- There were subtle conflicts between the various lists of spectra and lines which could be used. This has now been simplified with only `available_lines/spectra` now front facing. 
- `read_spectra` and `read_lines` are now only inputs and not stored. There are more intuitive ways to check if a Grid has spectra or lines.
- Properties have been introduced to flag if a `Grid` has lines and spectra. 
- A cloudy `reprocessed` flag has been introduced + a more informative error if someone tries to load lines from a grid without cloudy reprocessing.
- Line related function is now in `line` module.
- Functions …
> Giving grid.py some TLC

- src/synthesizer/components/blackhole.py
Fixing a bug were high-inclinations (i.e. obscured by the torus) didn't work properly.
- zeroed spectra were initialised with `np.zeros(grid.lam)` instead of `np.zeros(len(grid.lam))`
- Torus modelling needs the isotropic disc_incident spectra so have added this and used it.
- We now saved both the masked and unmasked `disc_incident` spectra. The masked is used to generate the "disc_escaped" spectra. Since `disc_incident` and `disc_incident_masked` are equivalent at low-inclination and `disc_incident_masked` is zero otherwise there is probably a better of way of handling this, for example, by multiplying `self.spectra["disc_incident"]` by the mask when used. However, this doesn't seem to work as the shapes are incorrect which is slightly puzzling and may point to a deeper issue.
- Bug
- …
> fixed issues with masks

- src/synthesizer/load_data/load_flares.py
The load_FLARES function previously didn't load the stellar smoothing lengths leading to errors in image creation. 
- Enhancement
> Load FLARES now loads stellar smoothing lengths

- src/synthesizer/filters.py
DWISOTT. Was not called by default on instantiation when it should have been.
- Bug
> Ensure filter resampling on new filter collection

- src/synthesizer/load_data/load_bluetides.py
- Bug
BlueTides ages are in Myr and the previous version of this script loaded them in in years instead.
> fixing BlueTides ages bug (yrs --> Myrs) (fresh clone with pre-commit hook)

- src/synthesizer/warnings.py
This PR introduces a `warnings` module (this could in the future include warnings for units, or any possible inconsistencies the user should know about).
Within the `warnings` module are a function and decorator that can be used for deprecations. The function can be called with a message to warn the user about future changes in functionality/ behaviour (e.g. changes in the expected argument type of a function, or something else more specific than a whole deprecated function). The decorator can be used to decorator deprecated functions. Both can take custom messages or categories but the decorator has a default that can be used most of the time.
- Enhancement
> Introduced a warnings module with a deprecation function and decorator

- src/synthesizer/components/stellar.py
- src/synthesizer/dust/attenuation.py
Fixes three small bugs:
- Removes the dust_curve specified in the default arguments inside get_spectra_CharlotFall
- Makes sure labels are properly propagated to downstream referenced spectra in `get_spectra_` methods
- In the Li+08 dust model, custom parameter values were always overwritten by the Milky Way values due to a bug in initialisation
- Bug
> Fix dust bugs

- src/synthesizer/components/stellar.py
- src/synthesizer/grid.py
- src/synthesizer/line.py
- src/synthesizer/parametric/stars.py
- src/synthesizer/particle/stars.py
A pretty minor improvement overall but this PR improves the intuitiveness of multi-line Lines. Previously a list or array of values for the individual lines making up a composite line was passed and stored. This required some logical gymnastics to make sure everything ended up where it needed to be in different situations. 
- Now a `Line` can be initialised using either an arbitrary number of `Line`s or the id, wavelength, luminosity and continuum that defines an individual line.
- Any individual lines used to create a new `Line` are stored in a `indiviudal_lines` attribute.
- A user-facing method to combine lines has been included for adding >2 lines together.
- `Line` addition has been fixed. It would have previously "run" but never would have given the correct answer unless you were …
> More intuitive multi-line `Line` objects (e.g. doublets).

- docs/source/imaging/parametric_imaging.ipynb
- src/synthesizer/imaging/image.py
Add's a method to produce a representation of `synthesizer` images mirroring the artwork used in Joy Division's seminal 1979 album Unknown Pleasures.
Example is includes in the docs, though it's currently based on a parametric galaxy and thus not particularly nice. The example below is based on TNG50.
- Bug
- Document
> Unknown pleasures

- src/synthesizer/components/stellar.py
- src/synthesizer/dust/attenuation.py
- src/synthesizer/particle/stars.py
Fixes a pair of bugs in the `get_particle_line_attenuated` and `get_particle_line_screen`.
- The attenuation felt by the line emission should *probably* just be `T_nebular` not `T_nebular * T_stellar`. I can see an argument for `T_nebular * T_stellar` if there is attenuation between the source and the nebular but that isn't consistently modelled by cloudy.
- Probably related to the above. For a screen `tau_v_nebular = tau_v_screen = tau_v`.
- A bigger bug was caused by the fact that `T_nebular` and `T_stellar` have shapes `(npart, 1)` for a line, not `(npart)` as assumed by the calculation.
- Also improved `component.stars.get_line_attenuated` by raising an exception if `tau_v_*` is not a float (e.g. if the user tries to provide an array as I did.
> Particle line fix

- src/synthesizer/line.py
- src/synthesizer/particle/stars.py
Adds a new method on `particles.stars` to generate dust attenuated spectra, in this case for a simple screen.
I have mistakenly also implemented line summing on this branch (fulfilling #610) too. No point separating it.
Closes #610.
> added method on stars to generate attenuated spectra and produce summed Lines and LineCollections

- src/synthesizer/particle/stars.py
Fixes `get_particle_spectra_screen` method by including a call to `_get_mask`.
> Fix masking for particle_spectra_screen method

- src/synthesizer/particle/galaxy.py
When loading stars or gas particles into a stars or gas component, previously if one of these arrays was not present (or spelled incorrectly) it would silently just return `None`. This adds an explicit warning, that can be disabled by setting verbosity to False.
- Enhancement
> Raise warning when particle arrays empty and setting stars or gas to none

- docs/source/abundances.ipynb
- src/synthesizer/particle/galaxy.py
- Enhancement
Related to #619, moved the verbose to init so user can suppress warnings on galaxy functions. Added warning to calculated_integrated_stellar_properties as that is used to calculte DTM ratios if using the L-Galaxy formula, and setting quantities to None. Also added warnings to calculate_integrated_gas_properties calculations and setting quantities to None.
> moved verbose to init, added more warnings

- src/synthesizer/filters.py
- src/synthesizer/parametric/stars.py
This PR refactors `Filter.apply_filter`. In essence the method is unchanged but is now a bit more robust. 
- Documentation has been improved.
- Can now integrate over `llam` or `flam` safely by passing `lam` to integrate over.
- Interpolation of the transmission curve onto the input x array is now done as standard (not just for observed arrays). This simplifies some of the logic but also makes the method safer since it will now correctly handles any input array.
- Enhancement
> Simplifies `Filter.apply_filter` slightly

- src/synthesizer/load_data/load_illustris.py
Adds a method for loading data from the TNG simulations.
Current implementation utilises the [`illustris_python` module](https://github.com/illustristng/illustris_python), which allows us to load in particles associated with individual subhalos one by one, rather than entire snapshot files. Whilst this is good for memory management (particularly for the very high resolution volumes) it is slightly slower than the masking approach used in other `load_data` methods. We may wish to implement multiple methods for loading TNG data in future, but for now this works.
- Enhancement
> Added method for loading TNG data

- src/synthesizer/filters.py
@aswinpvijayan uncovered a bug when loading a `FilterCollection`. Previously when loading filters the logic was constructed in such a way that `original_nu` would be overwritten by a nu derived from `self.lam` instead of the true original wavelengths. This was only ever an issue when loading SVO filters and previously didn't matter until `apply_filter` was updated to be more robust and use the correct x-axis during interpolation ( in #629).
This PR moves the filter loading onto an individual `Filter` and thus removes an ambiguity in the logic and workflow of loading a `Filter`.
- Bug
> Made sure Filters are loaded from a HDF5 file cleanly

- src/synthesizer/blackhole_emission_models.py
- src/synthesizer/components/stellar.py
- src/synthesizer/dust/emission.py
- src/synthesizer/filters.py
- src/synthesizer/grid.py
- src/synthesizer/particle/galaxy.py
- src/synthesizer/particle/gas.py
- src/synthesizer/particle/stars.py
- src/synthesizer/photoionisation/cloudy23.py
- src/synthesizer/sed.py
- src/synthesizer/units.py
- src/synthesizer/utils.py
- src/synthesizer/warnings.py
We've had a lot of rogue prints for a while now and they have led to large logs when running pipelines. Some of these were wrapped by a verbose flag but that was a half way house solution.
This PR introduces a wrapper around `warnings.warn` which now replaces all these rogue prints (only the prints which correspond to warning the user of something). 
The reason I have used a wrapper rather than just calling `warnings.warn` is so we can overload the default category and stack level instead of stating these in each warning. 
In the future we could expand on the default `RuntimeWarning` with specific Synthesizer warnings.
- Enhancement
> Converted prints to warnings

- src/synthesizer/extensions/los.c
- src/synthesizer/particle/gas.py
- Bug
Not necessarily a bug, just a logical choice of not setting a default DTM value when gas properties could be empty or None.
I have also modified los.c to state that we are calculating dust los surface density and not metal los surface density as stated before.
This closes issue #638
> Setting DTM=0.3 for None cases

- src/synthesizer/load_data/load_illustris.py
- src/synthesizer/particle/galaxy.py
- src/synthesizer/particle/particles.py
- src/synthesizer/sed.py
Supercedes #618.
This PR moves the method for integrating all particle spectra from solely on a galaxy to the components. This allows a user only working with components to quickly integrate all spectra. 
`Galaxy.integrate_particle_spectra` is now just a wrapper around the component versions.
- Enhancement
> Moved `intergrate_particle_spectra` to component level

- src/synthesizer/sed.py
DWISOTT. default is now None. Docstrong contains details on how to specify an attenuation model if required.
- Enhancement
> remove default IGM attenuation in get_fnu method

- src/synthesizer/load_data/load_camels.py
- src/synthesizer/load_data/load_illustris.py
Bug identified by @aliceemaffs where negative age star particles started appearing for certain CAMELS LH set simulations. Narrowed this down to a peculiar bug where the scale factor / redshift in the header is a 64 bit float, but formation times in the particle arrays are stored as 32 bit floats. This led to rounding errors when using astropy to convert to ages for non-zero redshift snapshots.
This PR fixes this bug for the TNG and Simba CAMELS simulations, as well as the TNG load data module. It is unclear what other simulations might be affected by this issue. 
- Bug
> Fix dtype issue for age calculations

- src/synthesizer/extensions/los.c
- src/synthesizer/kernel_functions.py
The current implementation of the los calculation is in the -z direction as opposed to +z, which was giving a different result from previous FLARES calculation. This is not necessarily an issue, but for consistency sake I have switched to the +z direction. 
Also increased the resolution of the default kernel from 1000 -> 10000 bins as we had in FLARES.
> Los orientation

- src/synthesizer/emission_models/agn/unified_agn.py
- src/synthesizer/sed.py
When a `Sed` is instantiated it automatically calculates bolometric luminosity. For large N-dimensional `Seds` this is very expensive and in many cases pointless because bolometric luminosity will not be used downstream.
In fact, most places that needed bolometric luminosity already called the method to do, making this a pointless doubling of work!
This PR closes #657.
- Enhancement
> Removing automatic bolometric luminosity calculation

- src/synthesizer/emission_models/stellar/pacman_model.py
- src/synthesizer/grid.py
`PacmanEmission` when provided a non reprocessed grid produced errors since the models that don't exist for a cloudy free grid were set erroneously to multiple `Nones`. However, the code should never have been able to get to this point. Turns out bad attribute naming meant the grid reprocessed flag got over written 😅 all fixed now.
- Bug
> Remove multiple returns for non-reprocessed grid in PacmanEmission

- docs/source/emission_models/custom_models.ipynb
- docs/source/spectra/blackholes.ipynb
- docs/source/spectra/galaxy.ipynb
- docs/source/spectra/stars.ipynb
- src/synthesizer/emission_models/__init__.py
- src/synthesizer/emission_models/base_model.py
- src/synthesizer/sed.py
The `EmissionModel` docs now discuss what the emitter argument is used for and demonstrates using the specialised `EmisisonModel` base classes for each emitter.
The docs also now demo using `get_spectra` to modify models for a single call. This is done specifically for optical depths on a stellar component and covering fractions on black holes although other possible modifications are discussed.
There's also a handful of very small fixes I came across in the process:
- `GalaxyEmissionModel` was missing from the `__init__.py` file.
- Latex legend labels weren't properly handled in `plot_spectra`.
- Covering fraction overriding wasn't fully implemented.
- Overides didn't actually handle the case where a float is passed, regardless of the fact the doc strings explicitly state they should …
> Improved the emission model docs to include emitter info and parameter overides

- docs/source/advanced/config_options.rst
- setup.py
Cosma's new OS gave rise to some installation issues when wanting to work with openMP. These are fixed by the introduction of `lib64` default library paths but I also added the ability to explicitly pass `include` directories.
- Enhancement
> Added some extra defaults and controls to the installation process 

- src/synthesizer/sed.py
This PR simply removes the `Quantities` which conflicted with the property methods designed to reduce the footprint of an `Sed`. Since these property methods use `Quantities` in their calculation they are already guaranteed to return the correct units.
Closes #649 
- Bug
> Removed conflicting Quantites from an Sed

- docs/source/spectra/galaxy.ipynb
- src/synthesizer/emission_models/base_model.py
Making it easier to control which spectra to save when the number of spectra is large.
- Enhancement
> Added a method to explicitly list spectra to save

- src/synthesizer/line.py
A bad error in attenuation checked the dimension of `line.luminosity` but erroneously tested this against a 2 (applicable for spectra) instead of a 1. This is now fixed.
- Bug
> BUGFIX: Fixed a bad error in line attenuation

- docs/source/grids/grids_example.ipynb
- src/synthesizer/grid.py
Removed the option to pass a FilterCollection to a grid that trancates the grid wavelength to the FilterCollection limits. This closes #681
> Removing passing a `FilterCollection` to a `Grid` to limit wavelengths.

- src/synthesizer/extensions/column_density.c
> BUGFIX: Removed broken args when compiling without openmp

- src/synthesizer/download_data.py
Download tool now can get only stellar test data (`--stellar-test-data`) or only agn test data (`--agn-test-data`).
Closes #672 
- Enhancement
> Introduced ability to get limit test data downloads

- src/synthesizer/emission_models/stellar/pacman_model.py
The intrinsic model was bugged in `PacmanEmission` when `fesc=0`. It now combines the correct models.
- Bug
> BUGFIX: Fixed `PacmanEmission` intrinsic model

- src/synthesizer/line.py
At present the `equivalent_width` is calculated on initialisation of a `Line` object. However, if the line or continuum luminosity is updated it will then be wrong. 
Instead I've replaced the attribute with a method and added the `@property` decorator. 
Closes #590.
> Replace equivalent_width attribute with method

- examples/cosmo/plot_test_age_lookup.py
- src/synthesizer/load_data/load_camels.py
- src/synthesizer/load_data/utils.py
Two changes:
- Bug fix in CAMELS loaders, where age lookup grid defined using fixed Planck+18 cosmology, rather than adopting cosmology from CAMELS sim.
- Changed from fixed resolution to a user defined $\Delta a$ (`delta_a`) in age lookup grid definition. Should make defining a grid resolution more 'physically motivated'
- Bug
- Enhancement
> Fix age lookup

- src/synthesizer/load_data/load_camels.py
- src/synthesizer/load_data/utils.py
- src/synthesizer/particle/stars.py
Fixes a small interpolation issue by locking the base of the grid on the scale factor of the snapshot being loaded.
Adds a check and error when loading ages into a particle stars object if those ages are negative.
- Bug
- Enhancement
> Age grid updates and check added

- src/synthesizer/particle/galaxy.py
- src/synthesizer/particle/stars.py
- src/synthesizer/warnings.py
The `deprecated` decorator was incorrectly defined for use with the optional arguments. This is now fixed.
- Bug
> Fixed deprecated arguments

- src/synthesizer/base_galaxy.py
- src/synthesizer/components/blackhole.py
- src/synthesizer/components/stellar.py
- src/synthesizer/particle/particles.py
I made a boo boo... forgot about `particle_photo_*` attributes. These are now deprecated in the same way instead of raising errors.
A couple of the deprecation warnings also had typos in them 😬 .
- Bug
> Overlooked some places deprecation was needed and fixed typo in warning

- src/synthesizer/particle/particles.py
- src/synthesizer/particle/stars.py
Instead of returning a `Line` containing arrays of zeros when all particles were masked out `Stars.generate_particle_line` returned a `Line` containing single zeros. This caused havoc downstream in the event this is ever triggered. Entertainingly this had already been addressed for black holes.
- Bug
> BUGFIX: `Stars.generate_particle_line` didn't handle entirely masked out arrays properly

- src/synthesizer/imaging/extensions/circular_aperture.c
- src/synthesizer/imaging/image.py
The aperture gave a perfect answer if the resolution was 1 and the image contained ones... like the test...
Turns out there was a bug left over from when I switched to using non-pixel coordinates that led to the summing being woefully incorrect if it was less than 0.5 🤦 
- Bug
> BUGFIX: Cautionary tale in using ones in tests (aperture fix)

- src/synthesizer/conversions.py
> `lnu_to_fnu` was missing from the conversions module

- src/synthesizer/particle/galaxy.py
- src/synthesizer/particle/gas.py
If the user provides no DTM then the DTM is assumed to be 0.3. If the user wants to use `dust_to_metal_vijayan19` to calculate the DTM they then call this but the dust mass computed at initialisation still exists and will be picked up during the LOS calculation, i.e. `dust_to_metal_vijayan19` only updated the DTM which had no effect on anything!
This PR fixes this by updating the `dust_masses`. I toyed with the idea of converting it to a property but that actually got quite messy, this is far simpler.
- Bug
> dust_to_metal_vijayan19 wouldn't necessarily update the dust masses

- src/synthesizer/emission_models/base_model.py
- src/synthesizer/emission_models/operations.py
- src/synthesizer/grid.py
Since the `Template` and corresponding emission model hadn't been used anywhere there were quite a few gremlins knocking about the code in relation to them. This PR fixes these gremlins and has been used and tested in the production of FLARES LRD observations as a test.
- Bug
> BUGFIX: Fixes various bugs when using a template

- .github/workflows/python-app.yml
- docs/source/emission_models/combined_models.ipynb
- docs/source/emission_models/model_usage.ipynb
- docs/source/imaging/particle_data_cube.ipynb
- docs/source/imaging/particle_imaging.ipynb
- docs/source/lines/galaxy_lines.ipynb
- docs/source/photometry/galaxy_phot.ipynb
- docs/source/spectra/blackholes.ipynb
- docs/source/spectra/stars.ipynb
- examples/blackholes/plot_single_bh_test.py
- examples/particle/plot_los_spectra.py
- profiling/image_strong_scaling.py
- profiling/spectral_cube_strong_scaling.py
- pyproject.toml
- src/synthesizer/base_galaxy.py
- src/synthesizer/components/blackhole.py
- src/synthesizer/components/stellar.py
- src/synthesizer/components/unified_agn.py
- src/synthesizer/emission_models/agn/unified_agn.py
- src/synthesizer/emission_models/base_model.py
- src/synthesizer/emission_models/operations.py
- src/synthesizer/emission_models/stellar/pacman_model.py
- src/synthesizer/particle/blackholes.py
- src/synthesizer/particle/stars.py
This PR introduces the `per_particle` flag to an `EmissionModel`. 
- Models that are per particle will now generate per particle emissions and then integrate them for all operations (e.g. extraction, combination, generation and attenuation).
- `EmissionModel._get_spectra` and the lines equivalent now carry a dictionary for integrated and per particle spectra to make later attachment easier.
- `get_particle_spectra` methods are now deprecated wrappers.
These changes allow the user to predefined which emissions they want to be per particle and which should be integrated. They also enable the mixing of per particle component emissions and galaxy level integrated emissions which previously had to be done in stages with different models.
- Enhancement
> Making per particle spectra an emission model attribute not a method choice

- src/synthesizer/components/blackhole.py
- src/synthesizer/emission_models/base_model.py
- src/synthesizer/emission_models/operations.py
- src/synthesizer/imaging/image.py
- src/synthesizer/particle/blackholes.py
- src/synthesizer/particle/gas.py
- src/synthesizer/particle/particles.py
- src/synthesizer/particle/stars.py
It's not uncommon when running a full simulation to find galaxies with no black holes (or even no stars or no gas depending on what analysis is being done). Previously Synthesizer would error in a bunch of strange ways in this eventuality. This PR adds a bunch of catches to ensure observables are still returned for empty components ensuring all downstream observables will be generated regardless.
- Enhancement
> Ensuring Synthesizer behaves predictably for galaxy with empty components

- src/synthesizer/emission_models/base_model.py
- src/synthesizer/emission_models/operations.py
- src/synthesizer/grid.py
- src/synthesizer/sed.py
This PR fixes a myriad of small bugs (and one huge bug). It also wraps calls to operations in try-except blocks to reraise the error with some more information about the emission that caused the error (although this could be done better and will be done better, we just need to get the bug fixes in ASAP).
- Optical depths were being double multiplied due to a bad copy paste. This is a dire bug but now fixed.
- `nansum` along with some nan masks are now used to avoid nans destroying sums with numerical values + some nan components (this could probably be expanded on).
- `Sed` resampling now also checks for nans and zeros them.
- Template scaling has been refactored slightly.
- Bug
> BUGFIX: Better handling of operation errors, NaNs, templates and optical depth fix

- src/synthesizer/download_data.py
- src/synthesizer/exceptions.py
Our test data host is currently down again. This PR introduces a fallback option using Dropbox. This isn't an ideal solution since Dropbox has a bandwidth limit and we could feasibly reach this reasonably often. However, as a quick fix and later a fallback option this will at least keep the wheel turning.
This also introduces a `DownloadError` for more obvious failures.
- Enhancement
> Introduce a fallback data mirror on dropbox to get around server failures (until we find a better host)

- src/synthesizer/sed.py
Grids have ndim > 2 (e.g. age, metallicity, wavelength). Some of the `sed` class methods strictly test for 2 dimensions, which leads them to break. This updates those checks, to handle sed objects with higher numbers of dimensions.
- Bug
> Handle sed objects with ndim > 2

- src/synthesizer/imaging/image.py
The imaging code has a dangerous coordinates check which can error when the weights are all zero. This check is actually redundant since 99% of the time centred coordinates are passed in and there are other checks that would handle the 1% rather than the "automatic fix" that was used. 
This PR removes this dangerous check.
- Bug
> Removing redundant coordinate shift in imaging

- src/synthesizer/filters.py
`Filter.apply_filter` never checked to ensure the non-zero masked array had elements (it now does, warns the user and returns 0), or checked if the array contribution in the band was 0 (if so there's no need to do the more expensive integration, this will now also return 0). 
- Bug
> BUGFIX: `apply_filter` could cause divide by zero errors

- docs/source/spectra/galaxy.ipynb
The galaxy spectra docs were a bit ugly due to the size of the emission tree plot.
This is a simple fix to that.
- Document
> Adjusting plot size to avoid overlapping models in galaxy spectra docs

- src/synthesizer/emission_models/operations.py
- src/synthesizer/grid.py
- src/synthesizer/parametric/stars.py
- src/synthesizer/sed.py
- src/synthesizer/utils/integrate.py
@stephenmwilkins found a bug where the result of `measure_bolometric_luminosity` differed from the numpy result but only when the `Sed` was sourced from `Grid.get_spectra` which did not previously associate units to the grid point it made the `Sed` from. It is unclear exactly what causes this but passing units (which would be best practice anyway) fixes this issue immediately.
- Bug
> BUGFIX: Fixing `Grid.get_spectra` edge case 

- src/synthesizer/download_data.py
While our server is proving more temperamental there's some unaccounted for errors which won't trigger falling back to dropbox. With this PR every exception except a `KeyboardInterrupt` will trigger falling back.
- Enhancement
> Catching more errors in downloads and redirecting to dropbox

- .github/workflows/python-app.yml
- docs/source/advanced/units.ipynb
- docs/source/emission_models/dust_emission.ipynb
- docs/source/sed/sed_example.ipynb
- src/synthesizer/emission_models/dust/emission.py
- src/synthesizer/emission_models/operations.py
- src/synthesizer/grid.py
- src/synthesizer/sed.py
- src/synthesizer/utils/integrate.py
- src/synthesizer/utils/util_funcs.py
- tests/test_sed.py
While ensuring the dust emission being generated was actually right I stumbled across some inconsistencies. To avoid these inconsistencies units are now used in the generation of spectra. Also:
- Doc strings have been cleaned up.
- `planck` has been "fixed" to produce spectral luminosity density rather than spectral radiance density. In reality this never mattered because the output was always normalised but meant the units were wrong (and would give an incorrect answer if called separately).
- Normalisation is now done consistently using `Sed` methods rather than `scipy`.
I've also updated the ruff workflow version to use the latest hash and fixed an issue introduced in #727 
- Bug
- Enhancement
> Ensuring unit consistency in Emission generators

- src/synthesizer/emission_models/agn/unified_agn.py
- src/synthesizer/emission_models/operations.py
Fixes a couple of bugs:
- When a parameter is fixed in an extraction it wasn't reset the parameter on the component. Since `cosine_inclination` is fixed as part of `UnifiedAGN` this led to this parameter being permanently changed.
- Some of the masking choices on `UnifiedAGN` was incorrect. The NLR should always be visible, and thus never masked.
- Bug
> Fixing some Unified AGN bugs

- src/synthesizer/parametric/blackholes.py
If a mask is None when passed to `_prepare_line_args` on a `BlackHole` the code would look for the `self.nbh` attribute on the `BlackHole` which doesn't exist because parametric black holes are always singular. This is now fixed.
Closes #735 
- Bug
> BUGFIX: Fixed mask behind the scenes mask generation for parametric BlackHole line generation

- src/synthesizer/parametric/blackholes.py
Adds `nbh` attribute to parametric blackholes to stop breaks elsewhere.
- Bug
> added nbh property to parametric blackholes

- docs/source/sed/sed_example.ipynb
- src/synthesizer/emission_models/agn/unified_agn.py
- src/synthesizer/emission_models/base_model.py
- src/synthesizer/emission_models/dust/emission.py
- src/synthesizer/grid.py
- src/synthesizer/sed.py
Adds `bolometric_luminosity` as a property method deprecating `measure_bolometric_luminosity`. This is less efficient since the quantity will always be calculated but, as we've seen, this is safer. 
I'm somewhat ambivalent about whether `measure_bolometric_luminosity` should be deprecated since it allows the bolometric luminosity to be calculated using different methods. However, we're probably never going to use anything other than trapezoid?!
TODO: find all other instances of `measure_bolometric_luminosity` and replace.
> Add bolometric luminosity as property

- src/synthesizer/emission_models/agn/unified_agn.py
This PR fixes an issue that only became apparent when testing the line emission functionality of the Unified AGN. This emerged because the scaling applied in the emission model was wrong. 
The best way of fixing this was deemed to be normalising the spectra, and line emission quantities, in the grid file by the isotropic bolometric luminosity. With this in place the scaling to be applied to the spectra is simply the bolometric luminosity of each BH. 
- This testing also suggests an independent bug (or physics) in the BLR modelling, likely at the cloudy modelling stage. I'm working to identify this but it is independent of this PR.
- This will require an update of the AGN test grid. However, that can probably wait until the BLR bug is caught since no one should be using the AGN modelling …
> Fixing the scaling in Unified AGN

- src/synthesizer/components/blackhole.py
- src/synthesizer/particle/blackholes.py
- src/synthesizer/particle/stars.py
When there are no particles, or all particles have been masked out, a comprehension is used to make all composite lines. This used to work by then unpacking it with a `*` into the `Line` itself but this was changed at some point to instead pass a tuple/list to `combine_lines`. These blocks hadn't been updated at that point.
- Bug
> BUGFIX: Fixing line unpacking when no lines can be made

- src/synthesizer/parametric/blackholes.py
- src/synthesizer/particle/blackholes.py
Remove the check for the grid to be associated with a line emitting region to allow the use of generic grids. This can be updated later with a check on the specific component type that the grid is made for. 
Closes #759
> Remove the check for the grid to be associated with a line emitting region to allow the use of generic grids

- src/synthesizer/load_data/load_eagle.py
- Bug
The previous version when loading the particle data did not correct for the periodic boundary. So in a few galaxies not all particles were being counted.
Also calculates the dust-to-metal ratio in the load and adds it to the galaxy.
> Fix for periodic boundary

- src/synthesizer/load_data/load_flares.py
Here I have added `read_abundances=False` as an argument for `load_flares()` since the Master file I had access to did not have the properties `Particle/S_Abundance_Oxygen` and `Particle/S_Abundance_Hydrogen`. 
- Enhancement
> Allow the loading of a Flares master file without abundances

- src/synthesizer/load_data/load_eagle.py
- src/synthesizer/particle/galaxy.py
- Bug
The eagle load_data will now use the redshift from the header rather than from the tag.
There was a bug in particle/galaxy.py in calculating the dust masses from the dust-to-metal ratio. There was a missing metallicity factor.
> using correct redshift from eagle header, plus bug in particle dust calculation

- src/synthesizer/load_data/load_camels.py
Small change, adds index to galaxy name for CAMELS Swift-EAGLE, which does some pre-filtering by mass for performance reasons, to allow easy look up down stream.
- Enhancement
> Add index for CAMELS Swift-EAGLE

- docs/source/getting_started/overview.rst
- src/synthesizer/base_galaxy.py
- Removed descriptions for the old arguments `stellar_photometry` and `blackhole_photometry` in `get_images_flux` as this confused me when searching the docs here: https://flaresimulations.github.io/synthesizer/_autosummary/synthesizer.base_galaxy.html#synthesizer.base_galaxy.BaseGalaxy.get_images_flux
- Fixed broken link to the Emission Models section here: https://flaresimulations.github.io/synthesizer/getting_started/overview.html
- Document
> Small fixes to the documentation

- docs/source/imaging/particle_imaging.ipynb
- src/synthesizer/base_galaxy.py
- src/synthesizer/components/component.py
Imaging methods were set up to return the root model image. If `limit_to` were passed then only that image would be generated and any error would be caused when indexing for the root when `limit_to` and the root model differ. This is now fixed.
- Bug
> Fixing `limit_to` argument in imaging methods

- src/synthesizer/units.py
When `accepts` was used with a list arg it was being appended to instead of having values set. This is now fixed.
- Bug
> BUGFIX: Fixing the accepts decorator for list/tuple args

- src/synthesizer/imaging/image.py
As stated in #801, you don't need to pass an extent when plotting a map since we already have the means to define the extent. This is now handled but the extent can be overridden if desired.
Closes #801 
- Enhancement
> Automatically calculate the extent when plotting a map

- src/synthesizer/grid.py
- src/synthesizer/parametric/stars.py
- src/synthesizer/utils/util_funcs.py
- tests/test_grid.py
`Grid` axes now handle extraction by via singular, plural, united, unitless and logged naming conventions. This lays the groundwork for using the new grid files while maintaining old behaviour with warnings.
Closes #530 
- Enhancement
> Updating grid axes to work for old and new grids

- docs/source/components/stars.ipynb
- examples/particle/plot_create_sampled_sed.py
- examples/particle/plot_single_star_test.py
- src/synthesizer/components/stellar.py
- src/synthesizer/parametric/stars.py
- src/synthesizer/particle/stars.py
#702 highlights a fundamental issue with how the instantaneous values were used to create SFZHs. This has now been modified to use the CIC machinery and will now give the expected result when computing statistics because the weights are correctly assigned, therefore closes #702. 
While doing this I also generalised things a bit better. Instead of a `Grid` you can now make SFZH for any arbitrary set of axes. I also introduced helpers for each individual axis (SFH and metallicity distributions) to make this a little easier.
- Bug
- Enhancement
> Refining instantaneous SFH and metallicity distributions (+ SFH and Z Dist helpers)

- src/synthesizer/emission_models/agn/models.py
- src/synthesizer/emission_models/agn/unified_agn.py
Added a check to ensure the sum of covering fractions does not exceed 1. 
Closes #732 
- Bug
> Added a safety check for covering fractions exceeding unity

- src/synthesizer/exceptions.py
- src/synthesizer/grid.py
- src/synthesizer/sed.py
Adds an attribute to the template to hold the unscaled "original" `Sed`. Also cleans up some logic by refining the overloaded multiplication of an `Sed` object. This means every type of scaler is handled up to the size of the `lnu` array and if an incompatible type is used, a helpful error is produced.
- Enhancement
> Some Quality of Life improvements to the `Template` 

- .github/workflows/python-app.yml
- .github/workflows/static.yml
- pyproject.toml
- src/synthesizer/parametric/sf_hist.py
Moves `dense_basis` to an optional install. This improves install time a bit and I think is justified. Should dense_basis related methods be called without the installation it'll raise an `UnmetDependency` error with installation instructions.
- Enhancement
> Moving dense_basis install to an optional dependency

- src/synthesizer/emission_models/stellar/models.py
This is a petty requirement. If you are using an emission model and want to test the dependence of your results on fesc, for example, then it will just fall over when it hits zero. Removed.
- Bug
> Remove requirement for intrinsic to have non-zero escape fraction

- .github/workflows/deploy.yml
- .github/workflows/python-app.yml
- .github/workflows/static.yml
- pyproject.toml
- src/synthesizer/load_data/load_illustris.py
You can't have optional dependencies that point at git repos on PyPi. 
This means `illustris_python` and `dense_basis` are now signposted to be installed from their repos if needed, instead of being explicit optional dependencies. Not a big problem really but a little less clean.
- Bug
> Modifications to make the pip deployment (hopefully) work

- .github/workflows/python-app.yml
Adding Python 3.13 to the matrix of versions tested. 
Note that 2 are tested at a time so moving from 3 versions to 4 carries no performance penalty.
- Enhancement
> Added version 3.13 to testing suite

- docs/source/advanced/config_options.rst
> Fix atomic timing docs typo

- src/synthesizer/grid.py
Closes #840.
Now `get_grid_point` maintains the axis order and also warns if the user passed unrecognised grid axes.
- Bug
> Fixes the ordering of returns on `get_grid_point`

- profiling/int_spectra_strong_scaling.py
- src/synthesizer/extensions/integrated_spectra.c
By swapping the parallelisation to an explicit chunking of the wavelength array we get fewer clashes and therefore scale better even when the number of particles is low. 
Here is a plot showing the improved scaling of the reduction step. This uses 1000 particles.
The green and red are the interesting parts here (the bits I've modified), you can see these are indeed now scaling. 
Very clearly there are other issues now. We are now dominated by "untimed overhead" for these low particle count galaxies (low in the grand scheme, the troubling thing is they are very run of the mill). Clearly some future work to do but do keep in mind this is all relative and the entire runtime is very small for these regardless.
For context here is a 100 times more particles:
- Enhancement
> Improving scaling of integrated spectra calculation

- profiling/int_spectra_strong_scaling.py
- src/synthesizer/emission_models/base_model.py
- src/synthesizer/particle/stars.py
- src/synthesizer/sed.py
We had been creating a `lam_mask` if we weren't passed one and then applying this regardless. It turns out this is a huge performance bottleneck. The mask is now only applied if it exists, removing the overhead unless it is actually required. 
In the future, we should move the masks into the C since an explicit skip (i.e. `if (!mask) continue`) will be far more efficient than manipulating masked data to be contiguous and also has the bonus that we can always work on fixed-size arrays.
This also fixes a bug where the user stated grid assignment method could be ignored.
Dependant on #844 
- Enhancement
> Removing `lam_mask` effects in argument preparation

- src/synthesizer/components/component.py
- src/synthesizer/emission_models/base_model.py
- src/synthesizer/emission_models/operations.py
- src/synthesizer/extensions/weights.c
- src/synthesizer/extensions/weights.h
This mildly improves the scaling of the weights calculation, although in real terms this only matters for very high particle counts. Below are plots showing the scaling for 1000 particles (where the weights calculation is ~1% the runtime) and 100000 particles where the weights calculation scales well (but highlights other problems for extreme particle counts).
Note that 10^6 particles finished in <0.1 second even without threading.
Depends on #845 
- Enhancement
> Improving scaling of the weights calculation

- src/synthesizer/base_galaxy.py
- src/synthesizer/components/blackhole.py
- src/synthesizer/components/component.py
- src/synthesizer/extensions/integrated_spectra.c
- src/synthesizer/parametric/blackholes.py
- src/synthesizer/particle/blackholes.py
- src/synthesizer/particle/particles.py
- src/synthesizer/particle/stars.py
- tests/test_spectra.py
We have previously never held onto the calculated weights grids when extracting spectra for several reasons (memory footprints, complexity with escape fractions and masks etc). However, now we have escape fractions decoupled from extractions this is easier to navigate.
This PR introduces caching of weight grids on a component, however, the weights are only cached and subsequently reused when not in the presence of a mask. This should reduce some overhead in duplicated calculations.
This is the 3rd attempt at this change and is the simplest approach yet (simply returning the grid of weights from the existing integrated spectra and attaching them). It's not clear to me why this works and using a dedicated weights function didn't. Functionally it doesn't matter but the latter would have been …
> Introduced simple caching of grid weights

- src/synthesizer/components/blackhole.py
- src/synthesizer/extensions/integrated_line.c
- src/synthesizer/extensions/integrated_spectra.c
- src/synthesizer/extensions/particle_line.c
- src/synthesizer/extensions/particle_spectra.c
- src/synthesizer/extensions/property_funcs.c
- src/synthesizer/extensions/property_funcs.h
- src/synthesizer/extensions/sfzh.c
- src/synthesizer/extensions/weights.c
- src/synthesizer/parametric/blackholes.py
- src/synthesizer/particle/blackholes.py
- src/synthesizer/particle/stars.py
This is another PR focus on performance and memory. It also another step towards simplifying the preparation methods in an attempt to limit the need for them.
Previously we've always created a mask if one wasn't passed, this is clearly bad from both a performance and memory standpoint. The reality is that its much cheaper to pass any mask into directly into the C extension (or pass None) and just skip elements which are masekd out. This also means that spectra will always explicitly always be the same shape.  
This PR implements this way of working with masks for spectra (omitting lines since a rewrite is immenent). 
- Enhancement
> Moving the masks into the C extensions to minimise memory

- pyproject.toml
DWISOTT 
Open PR fix [here](https://github.com/karllark/dust_extinction/pull/255).
- Bug
> Temporarily switching to a fork of dust_extinction to avoid setuptools-scm error
